"""
Report Registry — single source of truth for all report definitions.
Each entry drives parsing, filtering, display, and export behaviour.
"""

REPORTS = {

    # ── FUNNEL ──────────────────────────────────────────────────────────────

    "course_wise": {
        "label": "Course-Wise Funnel",
        "group": "Funnel",
        "file": "course_wise_data.csv",
        "header_row": 2,
        "drop_total": True,
        "trailing_empty_col": False,
        "dimension_col": "Institute",
        "columns": ["S.No.", "Institute", "Registered Applicants", "Paid Applicants"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants"],
        "computed_cols": {"Conversion %": ("Paid Applicants", "Registered Applicants")},
        "filter_cols": [],
        "multiselect_cols": ["Institute"],
        "date_cols": [],
        "description": "Registered vs Paid applicants across all MBA programmes.",
    },

    "course_wise_registration": {
        "label": "Course-Wise Registrations",
        "group": "Funnel",
        "file": "course_wise_registration.csv",
        "header_row": 2,
        "drop_total": True,
        "trailing_empty_col": True,
        "dimension_col": "Institute",
        "columns": ["S.No.", "Institute", "Registered Applicants"],
        "numeric_cols": ["Registered Applicants"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["Institute"],
        "date_cols": [],
        "description": "Registered applicants per programme.",
    },

    "course_wise_paid": {
        "label": "Course-Wise Paid",
        "group": "Funnel",
        "file": "course_wise_paid.csv",
        "header_row": 2,
        "drop_total": True,
        "trailing_empty_col": False,
        "dimension_col": "Institute",
        "columns": ["S.No.", "Institute", "Paid Applicants"],
        "numeric_cols": ["Paid Applicants"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["Institute"],
        "date_cols": [],
        "description": "Paid applicants per programme.",
    },

    # ── GEOGRAPHY ───────────────────────────────────────────────────────────

    "state_wise": {
        "label": "State-Wise",
        "group": "Geography",
        "file": "state_wise_data.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": False,
        "dimension_col": "StateWise",
        "columns": ["S.No.", "StateWise", "Registered Applicants", "Paid Applicants", "%"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants", "%"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["StateWise"],
        "date_cols": [],
        "description": "Applicants by state. Asterisk (*) denotes UT/special region.",
        "post_parse": "strip_state_asterisk",
    },

    "city_wise": {
        "label": "City-Wise",
        "group": "Geography",
        "file": "city_wise_data.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": False,
        "dimension_col": "CityWise",
        "columns": ["S.No.", "CityWise", "Registered Applicants", "Paid Applicants", "%"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants", "%"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["CityWise"],
        "date_cols": [],
        "description": "Applicants by city of residence.",
    },

    "snap_test_centres": {
        "label": "SNAP Test Centre Availability",
        "group": "Geography",
        "file": "TestDateWiseCityReport.csv",
        "header_row": 4,
        "drop_total": False,
        "trailing_empty_col": True,
        "dimension_col": "City Name",
        "columns": [
            "S.No", "City Name",
            "SNAP Test 1 Registered", "SNAP Test 1 Paid", "SNAP Test 1 Capacity", "SNAP Test 1 Available",
            "SNAP Test 2 Registered", "SNAP Test 2 Paid", "SNAP Test 2 Capacity", "SNAP Test 2 Available",
            "SNAP Test 3 Registered", "SNAP Test 3 Paid", "SNAP Test 3 Capacity", "SNAP Test 3 Available",
        ],
        "numeric_cols": [
            "SNAP Test 1 Registered", "SNAP Test 1 Paid", "SNAP Test 1 Capacity", "SNAP Test 1 Available",
            "SNAP Test 2 Registered", "SNAP Test 2 Paid", "SNAP Test 2 Capacity", "SNAP Test 2 Available",
            "SNAP Test 3 Registered", "SNAP Test 3 Paid", "SNAP Test 3 Capacity", "SNAP Test 3 Available",
        ],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": [],
        "date_cols": [],
        "description": "SNAP Test centre capacity, registrations, and availability by city across all 3 test dates.",
        "post_parse": "extract_state_from_city",
        "extra_filter_cols": ["State"],
    },

    # ── DEMOGRAPHICS ────────────────────────────────────────────────────────

    "category_wise": {
        "label": "Category-Wise (Reservation)",
        "group": "Demographics",
        "file": "category_wise.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": False,
        "dimension_col": "CategoryWise",
        "columns": ["S.No.", "CategoryWise", "Registered Applicants", "Paid Applicants", "%"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants", "%"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["CategoryWise"],
        "date_cols": [],
        "description": "Applicants by reservation category (OPEN, SC, ST, PWD, etc.).",
    },

    "gender_wise": {
        "label": "Gender-Wise",
        "group": "Demographics",
        "file": "gender_data.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": False,
        "dimension_col": "GenderWise",
        "columns": ["S.No.", "GenderWise", "Registered Applicants", "Paid Applicants", "%"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants", "%"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["GenderWise"],
        "date_cols": [],
        "description": "Applicants by gender.",
    },

    "education_type": {
        "label": "Education Type-Wise",
        "group": "Demographics",
        "file": "education_type_data.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": False,
        "dimension_col": "EducationTypeWise",
        "columns": ["S.No.", "EducationTypeWise", "Registered Applicants", "Paid Applicants", "%"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants", "%"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["EducationTypeWise"],
        "date_cols": [],
        "description": "Applicants by undergraduate stream / discipline.",
    },

    "experience_wise": {
        "label": "Experience-Wise",
        "group": "Demographics",
        "file": "experience_wise_data.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": False,
        "dimension_col": "ExperienceWise",
        "columns": ["S.No.", "ExperienceWise", "Registered Applicants", "Paid Applicants", "%"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants", "%"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["ExperienceWise"],
        "date_cols": [],
        "description": "Applicants split between freshers and experienced candidates.",
    },

    # ── PAYMENTS ────────────────────────────────────────────────────────────

    "payment_mode": {
        "label": "Payment Mode-Wise",
        "group": "Payments",
        "file": "payment_mode_data.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": False,
        "dimension_col": "Paymentmodewise",
        "columns": ["S.No.", "Paymentmodewise", "Registered Applicants", "Paid Applicants", "%"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants", "%"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["Paymentmodewise"],
        "date_cols": [],
        "description": "Applicants by payment instrument used (DD, Internet Banking, Easebuzz).",
    },

    "payment_mode_programme": {
        "label": "Payment Mode × Programme",
        "group": "Payments",
        "file": "PaymentModeWiseReport.csv",
        "header_row": 0,
        "drop_total": True,
        "trailing_empty_col": True,
        "dimension_col": "Programs",
        "columns": ["S.No", "Programs", "Paid Applicants", "Internet Banking", "Ease Buzz", "DD"],
        "numeric_cols": ["Paid Applicants", "Internet Banking", "Ease Buzz", "DD"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["Programs"],
        "date_cols": [],
        "description": "Cross-tab of paid applicants by programme and payment mode.",
    },

    "paid_by_date": {
        "label": "Payment Date-Wise",
        "group": "Payments",
        "file": "paid_wise_data.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": True,
        "dimension_col": "Paidwise",
        "columns": ["S.No.", "Paidwise", "Paid Applicants"],
        "numeric_cols": ["Paid Applicants"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": [],
        "date_cols": ["Paidwise"],
        "description": "Daily payment volume — date applicants completed payment.",
    },

    "registration_by_date": {
        "label": "Registration Date-Wise",
        "group": "Payments",
        "file": "registration_by_date_data.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": False,
        "dimension_col": "DateWise",
        "columns": ["S.No.", "DateWise", "Registered Applicants", "Paid Applicants", "%"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants", "%"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": [],
        "date_cols": ["DateWise"],
        "description": "Daily registration and payment activity.",
    },

    # ── NRI / INTERNATIONAL ─────────────────────────────────────────────────

    "nri_candidate": {
        "label": "NRI Candidate Flag",
        "group": "NRI / International",
        "file": "nri_data.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": False,
        "dimension_col": "NRI_candidate",
        "columns": ["S.No.", "NRI_candidate", "Registered Applicants", "Paid Applicants", "%"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants", "%"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["NRI_candidate"],
        "date_cols": [],
        "description": "Applicants flagged as NRI candidates (Yes/No).",
    },

    "admission_nri": {
        "label": "Admission Under NRI Quota",
        "group": "NRI / International",
        "file": "admission_nri.csv",
        "header_row": 2,
        "drop_total": False,
        "trailing_empty_col": False,
        "dimension_col": "Admission_under_NRI",
        "columns": ["S.No.", "Admission_under_NRI", "Registered Applicants", "Paid Applicants", "%"],
        "numeric_cols": ["Registered Applicants", "Paid Applicants", "%"],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["Admission_under_NRI"],
        "date_cols": [],
        "description": "Applicants admitted under the NRI quota.",
    },

    # ── STUDENT DETAIL ───────────────────────────────────────────────────────

    "paid_students_snap": {
        "label": "Paid Students — SNAP City Details",
        "group": "Student Detail",
        "file": "PaidStudentswithTestWiseCityDetails.csv",
        "header_row": 0,
        "drop_total": False,
        "trailing_empty_col": True,
        "dimension_col": "Name",
        "columns": ["ApplicantID", "Name", "Test", "Test City 1", "Test City 2", "Test City 3"],
        "numeric_cols": [],
        "computed_cols": {},
        "filter_cols": [],
        "multiselect_cols": ["Test City 1", "Test City 2", "Test City 3"],
        "date_cols": [],
        "description": "Individual paid applicants with their SNAP test city preferences.",
        "post_parse": "parse_snap_tests",
        "text_search_cols": ["ApplicantID", "Name"],
    },
}

# Group ordering for sidebar
GROUP_ORDER = ["Funnel", "Geography", "Demographics", "Payments", "NRI / International", "Student Detail"]
